---
- name: Ruby development environment
  hosts: all
  tasks:

  - name: Make sure dpkg frontend lock is released
    command: lsof /var/lib/dpkg/lock-frontend
    register: result
    failed_when: false
    changed_when: false
    until: result.rc != 0
    retries: 20
    delay: 10
    become: true
    when: ansible_facts["os_family"] == "Debian"

  - name: Install apt packages
    apt:
      name: ["build-essential"]
      update_cache: yes
      # 1 hour
      cache_valid_time: 3600
    become: true
    when: ansible_facts["os_family"] == "Debian"

  - name: Add user 'vagrant' to group 'vboxsf'
    become: true
    user:
      name: vagrant
      groups: vboxsf
      append: yes
    when: ansible_facts["virtualization_type"] == "virtualbox"

  - name: Mount shared folder
    become: true
    mount:
      path: /mnt/packer-mikrotik
      src: packer-mikrotik
      fstype: vboxsf
      opts: rw,exec,uid=vagrant,gid=vboxsf,dmode=775,fmode=664
      state: mounted
    when: ansible_facts["virtualization_type"] == "virtualbox"

  - name: Ensure Ruby 2.7 build enviromment is present
    become: true
    ansible.builtin.dnf:
      name: "{{ item }}"
    loop:
      - "@ruby:2.7"
      - ruby-devel
    when: ansible_facts["os_family"] == "RedHat"

  - name: Install Ruby snap
    become: true
    # community.general.snap:
    # (fails since we are using ansible_local provisioner and it installs old Ansible version)
    snap:
      name: ruby
      channel: 2.7/stable # otherwise 3.1.2 is installed and vagrant 2.2.20.dev depends on (>= 2.6, < 3.1)
      classic: yes
    when: ansible_facts["os_family"] == "Debian"

    # Not installing since rvm.ruby fails
    # - name: Install roles from Ansible Galaxy
    #   command: ansible-galaxy install {{ item }}
    #   with_items:
    #     - "rvm.ruby"
    #   become: true

  # This used to work, but now (25.04.22) fails on "Import GPG keys from keyservers"
  # We are using snap for ruby installation, leaving this for the reference
  # roles:
  #   - name: Install ruby
  #     role: rvm.ruby
  #     rvm1_rubies: ['ruby-3.1.2']
  #     rvm1_user: 'vagrant'
